### ISSUE TITLE
Metabolism full screen view not working

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#1126] opened 2019-05-24 11:01 UTC
e..g https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL192/
from here trying to select "see in full screen" returns an 404 error page not found.  Please could you look into this.

**Comment by nclopezo** [comment] 2019-05-24 11:05
Duplicate of https://github.com/chembl/GLaDOS/issues/1004

**Closed by nclopezo** 2019-05-24 11:05 UTC
Labels: bug
