### ISSUE TITLE
Compound report card - order of sections

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#337] opened 2017-10-16 08:04 UTC
Can we order the sections as on the existing interface?

Certainly molecule features, clinical data & alternative forms should be higher, calculated properties lower...

**Comment by nclopezo** [comment] 2017-11-13 16:35
**This can be closed if approved.**
The sections have been reordered as it is in the current interface. I am aware that some sections are missing, but there are already issues about that (#7, #28, #301)

**Comment by nclopezo** [comment] 2017-11-13 16:37
https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL25/

**Comment by agaulton** [comment] 2017-11-20 10:11
I got an error on loading CHEMBL25 (see screen shot) the first time, and the second time too really long...
![cpd_report_error](https://user-images.githubusercontent.com/7058697/33012499-0875a20e-cdd9-11e7-9582-989f32a7c482.jpeg)

Otherwise, the order looks fine. I think there is an issue with the Assay pie chart - will make a separate issue...

**Comment by nclopezo** [comment] 2017-11-20 10:44
That error is caused by what is described in https://github.com/chembl/GLaDOS/issues/451. We have seen that it is related to some browser caching (we still need to investigate). It should "magically fix" later today.

**Comment by mnowotka** [comment] 2017-11-20 14:02
I'm closing this one, it the problem with error persists, please open a ticket.

**Closed by mnowotka** 2017-11-20 14:02 UTC
Labels: compounds, enhancement, report cards, status-pending-approval
