### ISSUE TITLE
Compound report card - Mechanism of action

### ISSUE THREAD

**Issue by mpaulam** [chembl/GLaDOS#1097] opened 2019-04-10 14:22 UTC
The molecule CHEMBL2108576 has a mechanism of action in the database but it's not appearing in the report card:

https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL2108576/

This doesn't happen with every molecule, for example this one shows the mechanism in the report card: CHEMBL1655.

The mechanism of action does appear in the Browse mechanism of action table.

**Comment by agaulton** [comment] 2019-05-23 08:52
doesn't even seem to be a problem for all antibodies, so need to work out why this one is missing...

**Comment by agaulton** [comment] 2019-05-23 08:57
Ok, seems the problem is that the mechanism section is only being shown for approved drugs, but it should also be included for phase 0-3 drugs where it exists.

**Comment by anne123** [comment] 2019-07-29 15:16
David/Juan do you know when this can be fixed? I have also found some examples of this today.  It seems quite important to me.

**Comment by nclopezo** [comment] 2019-07-29 15:55
This section is shown only if metadata.hierarchy.is_approved_drug is true. For CHEMBL2108576 this is false so the section is not shown. Should we keep that rule? or should we review the way metadata.hierarchy.is_approved_drug is calculated? A recalculation of metadata.hierarchy.is_approved_drug will require a reindexation @juanfmx2

**Comment by anne123** [comment] 2019-07-29 16:01
See Anna's comment above - it should be included for everything where the mechanism is known not just Phase 4.

**Comment by nclopezo** [comment] 2019-07-29 16:03
Sorry, I didn't see [Anna's comment](https://github.com/chembl/GLaDOS/issues/1097#issuecomment-495129621), It's fixed here https://github.com/chembl/GLaDOS/pull/1168. If It passess the tests It should be ready tomorrow in the morning. 
It will now be shown if metadata.hierarchy.is_approved_drug is true or max_phase <= 3

**Comment by nclopezo** [comment] 2019-07-29 16:12
After talking to @anne123, it will be shown for all cases where there is data, see https://github.com/chembl/GLaDOS/pull/1169

**Comment by nclopezo** [comment] 2019-07-30 09:30
This is fixed now:
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL2108576/

**Closed** 2019-07-31 14:38 UTC
Labels: bug
