### ISSUE TITLE
csv, tsv download

### ISSUE THREAD

**Issue by ARLEBI** [chembl/GLaDOS#361] opened 2017-10-18 11:26 UTC
Download option doesn't seem to work. I had a couple of related targets (A2A from human and rat) with reported compound activities but could not download the data using the csv, tsv icons. There was a message "generating file" but then nothing more.

**Comment by nclopezo** [comment] 2017-10-19 11:36
Hi Andrew, 

I tried to reproduce it but I wasn't able to do it. 
I visited this url:
https://chembl-glados.herokuapp.com/search_results/targets/A2A
Then selected with the filters "Homo Sapiens" and "Ratus Norgevigus" , and the download worked for me. 
<img width="1416" alt="screen shot 2017-10-19 at 12 32 41" src="https://user-images.githubusercontent.com/1944922/31769073-f0743a1c-b4c9-11e7-87af-45275858fb9b.png">

Is there some extra step that I am missing?

**Comment by ARLEBI** [comment] 2017-10-19 15:24
I selected the two targets, clicked on the Bioactivity icon to display a heat map and then tried to download. It showed “generating file” but nothing happened beyond that – no obvious place to click to download the file.
Andrew

**Comment by nclopezo** [comment] 2017-10-25 15:46
This should be fixed now.

**Comment by mnowotka** [comment] 2017-10-30 11:21
The bug seems to be fixed but there is another issue of downloading data from the heatmap. This issue will be addressed separately in #398 so I'm closing this ticket.

**Closed by mnowotka** 2017-10-30 11:21 UTC
Labels: bug, downloads
