### ISSUE TITLE
search by chemblid or search by drug name inconsistency

### ISSUE THREAD

**Issue by nbosc** [chembl/GLaDOS#145] opened 2017-06-07 14:01 UTC
Currently, when you search CHEMBL1542, you get the 4 compound versions. However, when you search for AZATHIOPRINE, you get only 2 versions.

Don't you think, both queries should return the same thing?

**Comment by mnowotka** [comment] 2017-10-13 16:02
This looks to me like a duplicate of #114 but feel free to reopen it that's not the case.

**Closed by mnowotka** 2017-10-13 16:02 UTC
Labels: duplicate
